### PR TITLE
Increasing doc page content.

### PR DESCRIPTION
**Pull request by tbfreitas**
Adding sample use from generate functions.

### CODE REVIEW

**Review by hyanmandian — CHANGES_REQUESTED** [review]
You don't need to change this file.

**Comment by hyanmandian** [comment]
Hello @tbfreitas nice contribution! Can you update pt-BR docs too?

**Comment by hyanmandian** [comment]
@all-contributors please add @tbfreitas for docs.

**Comment by tbfreitas** [comment]
> Hello @tbfreitas nice contribution! Can you update pt-BR docs too?



> @all-contributors please add @tbfreitas for docs.



> Hello @tbfreitas nice contribution! Can you update pt-BR docs too?

Sure I can. 
I`m gonna do it as soon as I can.

**Comment by tbfreitas** [comment]
> Hello @tbfreitas nice contribution! Can you update pt-BR docs too?

Done, my friend.
So I also did a little fix on function exposing on general docs.

**Comment by tbfreitas** [comment]
> Sorry @tbfreitas, I accidentally removed all-contributors-rc... Can you revert that change and keep this file equals main branch?
> 
> Just to heads up, we have a bot to do these updates, you can check #228 here.

Not problem at all, I already put it back.
I also had forgot to back it to main branch version..

**Review by hyanmandian — APPROVED** [review]

**Comment by hyanmandian** [comment]
Thanks for your contribution @tbfreitas !

**Pull request merged**
