### PR TITLE
Add CEP formatter

### PR DESCRIPTION
**Pull request by rfoel**
I found the need to have a CEP formatter to get the data from APIs and display to the user. Some of the data have nothing but digits and others have a dot in them. This package should work for both cases.

### CODE REVIEW

**Comment by hyanmandian** [comment]
Welcome @rfoel and a nice job! Right now we are working on a refactoring of the entire library, can you send this PR to #63 ? Maybe you should do some changes on your code to follow the new structure, but I think that's easy (if you have some problem I can help you on that).

Thanks!

**Comment by rfoel** [comment]
@hyanmandian sure thing. But wouldn't be smarter to keep deploying versions while refactoring? It seems to be stale for one month the development of #63. I'm afraid this refactor takes longer than it should.

**Comment by hyanmandian** [comment]
You right, I'll check if we can publish your package. On the other hand, can you send this PR to # 63 too? I'm trying to focus on these changes to publish ASAP the next version.

**Comment by hyanmandian** [comment]
I merged #63 and I'll check which packages are missing and today or tomorrow I publish the next version.

**Comment by rfoel** [comment]
@hyanmandian all right. I'll open a PR later today.

**Pull request closed without merging**
