### PR TITLE
Project refactoring as a single package with tree-shaking

### PR DESCRIPTION
**Pull request by andreoav**
🚧 This is a working in progress 🚧

# Introduction

This PR proposes a new project structure removing the lerna monorepo and merging everything in a single package that supports tree-shaking.

- [x] Migrate all packages to the new structure
- [ ] Code optimization and refactoring
- [ ] Rebase master into this branch to get the latest updates
- [ ] Update documentation
- [ ] Restore existing contributors
- [ ] Generate a pre-release
- [ ] Automate the publishing process
- [ ] Final release

❗️ IMPORTANT: This PR **DO NOT RESET THE REPOSITORY HISTORY**, otherwise all commits from all contributors will be lost.

### CODE REVIEW

**Comment by andreoav** [comment]
@hyanmandian @lucassveloso what do you think?

**Comment by hyanmandian** [comment]
Sounds good for me and I think that we can use this refatoring to fix issues like #38 #29 #37

**Comment by vhfmag** [comment]
How is this going? Let me know if I can help :smile:

**Comment by andreoav** [comment]
@vhfmag I was working on other things and didn't have the time to finish this one, but now I'm available again and I'll to aim to finish this next week.

Feel free to contribute, I appreciate your help.

**Comment by fxamauri** [comment]
if you want to add me on this pull request, I do the #42 and #41 in the new structure :+1:

**Comment by andreoav** [comment]
@hyanmandian What do you think about use https://github.com/palmerhq/tsdx in this refactoring?

**Comment by andreoav** [comment]
Added a new proposal to replace this one. #49

**Comment by hyanmandian** [comment]
Closed in favor of #49

**Pull request closed without merging**
